# Generated by Django 4.2.16 on 2024-11-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('suggested_format', models.CharField(max_length=250)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=250)),
                ('grade', models.CharField(max_length=250)),
                ('strand', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('lesson_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('objectives', models.TextField()),
                ('materials', models.TextField()),
                ('links', models.URLField(max_length=250)),
                ('assessment', models.TextField()),
                ('curricular_barriers', models.TextField()),
                ('options_for_engagement', models.TextField()),
                ('options_for_representation', models.TextField()),
                ('options_for_action_and_expression', models.TextField()),
                ('iep_goals', models.TextField()),
                ('scripting_of_lesson', models.TextField()),
                ('standards', models.ManyToManyField(to='backend.standard')),
            ],
        ),
    ]
